name: synology-media-stack-setup

services:
  setup-ui:
    build:
      context: ./setup-ui
    ports:
      - 8080:8080
    volumes:
      - ./:/repo
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_ROOT=/repo
    restart: unless-stopped
