name: synology-media-stack-setup

services:
  setup-ui:
    build:
      context: ./setup-ui
    ports:
      - 3000:3000
    volumes:
      - ./:/repo
    environment:
      - SETUP_UI_REPO_ROOT=/repo
    restart: unless-stopped
