import os
from pathlib import Path
from flask import Flask, Response, render_template, request

app = Flask(__name__)

DEFAULTS = {
    "APPDATA_ROOT": "/volume1/docker/appdata",
    "DATA_ROOT": "/volume1/data",
    "TRANSCODE_ROOT": "/volume1/docker/transcode",
    "PUID": "1026",
    "PGID": "100",
    "TZ": "America/Chicago",
    "PLEX_CLAIM": "",
}


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def build_env_text(values: dict[str, str]) -> str:
    def get(key: str) -> str:
        return values.get(key, "").strip()

    # Keep the file minimal and predictable. No secrets are stored server-side.
    lines = [
        "# Generated by setup-ui (do not commit this file)",
        "",
        f"APPDATA_ROOT={get('APPDATA_ROOT')}",
        f"DATA_ROOT={get('DATA_ROOT')}",
        f"TRANSCODE_ROOT={get('TRANSCODE_ROOT')}",
        "",
        f"PUID={get('PUID')}",
        f"PGID={get('PGID')}",
        f"TZ={get('TZ')}",
        "",
        "# Optional. Only needed once to claim Plex.",
        f"PLEX_CLAIM={get('PLEX_CLAIM')}",
        "",
        "# Optional. Usually not needed with Plex host networking.",
        "ADVERTISE_IP=",
        "",
    ]
    return "\n".join(lines)


@app.get("/")
def index():
    # If the repo is mounted, use .env.example to prefill defaults.
    repo_env_example = Path(os.environ.get("REPO_ENV_EXAMPLE", "/repo/.env.example"))
    file_defaults = parse_env_file(repo_env_example)

    merged = dict(DEFAULTS)
    merged.update({k: v for k, v in file_defaults.items() if v is not None})

    return render_template("index.html", defaults=merged)


@app.post("/download")
def download():
    values = {
        "APPDATA_ROOT": request.form.get("APPDATA_ROOT", ""),
        "DATA_ROOT": request.form.get("DATA_ROOT", ""),
        "TRANSCODE_ROOT": request.form.get("TRANSCODE_ROOT", ""),
        "PUID": request.form.get("PUID", ""),
        "PGID": request.form.get("PGID", ""),
        "TZ": request.form.get("TZ", ""),
        "PLEX_CLAIM": request.form.get("PLEX_CLAIM", ""),
    }

    env_text = build_env_text(values)

    return Response(
        env_text,
        mimetype="text/plain; charset=utf-8",
        headers={
            "Content-Disposition": 'attachment; filename=".env"',
            "Cache-Control": "no-store",
        },
    )


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "8080"))
    # LAN-only by default.
    app.run(host="0.0.0.0", port=port, debug=False)
