const express = require('express');
const path = require('path');
const fs = require('fs');
const https = require('https');
const http = require('http');
const os = require('os');

// Startup banner
console.log('');
console.log('╔══════════════════════════════════════════════════════════════╗');
console.log('║                    Eden Viewer Setup UI                       ║');
console.log('║                        v1.0.0                                 ║');
console.log('╚══════════════════════════════════════════════════════════════╝');
console.log('');

console.log('[1/7] 🔧 Loading environment configuration...');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

console.log('[2/7] 📦 Initializing Express application...');
const app = express();
const PORT = process.env.SETUP_UI_PORT || 3000;

console.log('[3/7] ⚙️  Configuring middleware...');
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// Request logging middleware
app.use((req, res, next) => {
  const timestamp = new Date().toISOString();
  console.log(`[${timestamp}] ${req.method} ${req.path}`);
  next();
});

console.log('[4/7] 🛤️  Registering API routes...');

// API: Health check endpoint
app.get('/api/health', (req, res) => {
  res.json({ 
    status: 'healthy',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    version: '1.0.0'
  });
});

// API: Check if Plex is accessible
app.get('/api/plex-status', async (req, res) => {
  const plexHost = req.query.host || req.hostname;
  const plexPort = req.query.port || 32400;
  const plexUrl = `http://${plexHost}:${plexPort}/identity`;
  
  console.log(`  ├─ Checking Plex connectivity: ${plexUrl}`);
  
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 5000);
    
    const response = await fetch(plexUrl, { 
      signal: controller.signal,
      headers: { 'Accept': 'application/json' }
    });
    clearTimeout(timeout);
    
    if (response.ok) {
      console.log('  └─ ✅ Plex is running');
      res.json({ online: true, url: `http://${plexHost}:${plexPort}/web` });
    } else {
      console.log(`  └─ ⚠️ Plex responded with status ${response.status}`);
      res.json({ online: false, error: `HTTP ${response.status}` });
    }
  } catch (error) {
    console.log(`  └─ ❌ Plex not reachable: ${error.message}`);
    res.json({ online: false, error: error.message });
  }
});

// API: Get current configuration status
app.get('/api/status', (req, res) => {
  const envPath = path.join(__dirname, '..', '.env');
  const configExists = fs.existsSync(envPath);
  
  console.log(`  ├─ Config check: ${configExists ? 'Found' : 'Not found'} (${envPath})`);
  
  res.json({
    configured: configExists,
    domain: process.env.PLEX_DOMAIN || null,
    environment: process.env.DEPLOYMENT_TARGET || 'synology'
  });
});

// API: Save configuration
app.post('/api/configure', (req, res) => {
  const { domain, puid, pgid, timezone, deploymentTarget } = req.body;
  
  console.log('  ├─ Configuration request received:');
  console.log(`  │  ├─ Domain: ${domain}`);
  console.log(`  │  ├─ PUID: ${puid}`);
  console.log(`  │  ├─ PGID: ${pgid}`);
  console.log(`  │  ├─ Timezone: ${timezone}`);
  console.log(`  │  └─ Target: ${deploymentTarget}`);
  
  const envContent = `# Eden Viewer Configuration
# Generated by Setup UI on ${new Date().toISOString()}

# Custom Domain for HTTPS/TLS
PLEX_DOMAIN=${domain || 'viewer.kellzkreations.com'}

# Container User/Group IDs
PUID=${puid || '1000'}
PGID=${pgid || '1000'}

# Timezone
TZ=${timezone || 'America/New_York'}

# Deployment Target (synology or azure)
DEPLOYMENT_TARGET=${deploymentTarget || 'synology'}
`;

  try {
    const envPath = path.join(__dirname, '..', '.env');
    fs.writeFileSync(envPath, envContent);
    console.log(`  └─ ✅ Configuration saved to ${envPath}`);
    res.json({ success: true, message: 'Configuration saved' });
  } catch (error) {
    console.error(`  └─ ❌ Failed to save configuration: ${error.message}`);
    res.status(500).json({ success: false, message: error.message });
  }
});

// Serve OOBE UI
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

console.log('[5/7] 🔐 Checking TLS certificate configuration...');

const certFile = process.env.SETUP_UI_CERT_FILE;
const keyFile = process.env.SETUP_UI_KEY_FILE;
const hasCerts = certFile && keyFile && fs.existsSync(certFile) && fs.existsSync(keyFile);

if (hasCerts) {
  console.log(`  ├─ Certificate: ${certFile}`);
  console.log(`  └─ Private Key: ${keyFile}`);
} else {
  console.log('  └─ No TLS certificates configured (using HTTP)');
}

console.log('[6/7] 🌐 Detecting network interfaces...');

const networkInterfaces = os.networkInterfaces();
const addresses = [];
Object.keys(networkInterfaces).forEach((ifname) => {
  networkInterfaces[ifname].forEach((iface) => {
    if (iface.family === 'IPv4' && !iface.internal) {
      addresses.push({ name: ifname, address: iface.address });
    }
  });
});

if (addresses.length > 0) {
  addresses.forEach((addr, idx) => {
    const prefix = idx === addresses.length - 1 ? '└─' : '├─';
    console.log(`  ${prefix} ${addr.name}: ${addr.address}`);
  });
} else {
  console.log('  └─ No external network interfaces found');
}

console.log('[7/7] 🚀 Starting HTTP server...');
console.log('');

// Start server
if (hasCerts) {
  const options = {
    cert: fs.readFileSync(certFile),
    key: fs.readFileSync(keyFile)
  };
  https.createServer(options, app).listen(PORT, () => {
    printStartupComplete('https', PORT, addresses);
  });
} else {
  http.createServer(app).listen(PORT, () => {
    printStartupComplete('http', PORT, addresses);
  });
}

function printStartupComplete(protocol, port, addresses) {
  console.log('╔══════════════════════════════════════════════════════════════╗');
  console.log('║                    ✅ Server Ready                           ║');
  console.log('╠══════════════════════════════════════════════════════════════╣');
  console.log(`║  Protocol:  ${protocol.toUpperCase().padEnd(48)}║`);
  console.log(`║  Port:      ${port.toString().padEnd(48)}║`);
  console.log('╠══════════════════════════════════════════════════════════════╣');
  console.log('║  Access URLs:                                                ║');
  console.log(`║    Local:   ${protocol}://localhost:${port}/`.padEnd(63) + '║');
  
  addresses.forEach((addr) => {
    const url = `${protocol}://${addr.address}:${port}/`;
    console.log(`║    ${addr.name}:`.padEnd(12) + url.padEnd(51) + '║');
  });
  
  console.log('╠══════════════════════════════════════════════════════════════╣');
  console.log('║  API Endpoints:                                              ║');
  console.log('║    GET  /api/health    - Health check                        ║');
  console.log('║    GET  /api/status    - Configuration status                ║');
  console.log('║    POST /api/configure - Save configuration                  ║');
  console.log('╠══════════════════════════════════════════════════════════════╣');
  
  if (protocol === 'http') {
    console.log('║  ⚠️  Running without TLS - Set SETUP_UI_CERT_FILE and        ║');
    console.log('║     SETUP_UI_KEY_FILE environment variables for HTTPS       ║');
  } else {
    console.log('║  🔒 TLS enabled - Connection is secure                       ║');
  }
  
  console.log('╚══════════════════════════════════════════════════════════════╝');
  console.log('');
  console.log('Press Ctrl+C to stop the server');
  console.log('');
}

// Graceful shutdown
process.on('SIGINT', () => {
  console.log('');
  console.log('🛑 Received SIGINT signal');
  console.log('👋 Shutting down Eden Viewer Setup UI...');
  process.exit(0);
});

process.on('SIGTERM', () => {
  console.log('');
  console.log('🛑 Received SIGTERM signal');
  console.log('👋 Shutting down Eden Viewer Setup UI...');
  process.exit(0);
});
