"""
Unit tests for Setup UI Flask app (app.py)
"""

import pytest
from pathlib import Path
from app import (
    app,
    _sanitize_env_value,
    _sanitize_numeric,
    parse_env_file,
    build_env_text,
    DEFAULTS,
)


@pytest.fixture
def client():
    """Create a test client for the Flask app"""
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client


def test_sanitize_env_value():
    """Test environment value sanitization"""
    # Test normal values
    assert _sanitize_env_value("test") == "test"
    assert _sanitize_env_value("  test  ") == "test"
    
    # Test newline removal
    assert _sanitize_env_value("test\nvalue") == "testvalue"
    assert _sanitize_env_value("test\r\nvalue") == "testvalue"
    assert _sanitize_env_value("line1\nline2\rline3") == "line1line2line3"
    
    # Test empty values
    assert _sanitize_env_value("") == ""
    assert _sanitize_env_value("   ") == ""


def test_sanitize_numeric():
    """Test numeric value sanitization"""
    from werkzeug.exceptions import BadRequest
    
    # Valid numeric values
    assert _sanitize_numeric("123") == "123"
    assert _sanitize_numeric("  456  ") == "456"
    assert _sanitize_numeric("1000") == "1000"
    
    # Invalid numeric values should abort with 400
    with pytest.raises(BadRequest):
        _sanitize_numeric("abc")
    
    with pytest.raises(BadRequest):
        _sanitize_numeric("12.5")
    
    with pytest.raises(BadRequest):
        _sanitize_numeric("1a2")


def test_parse_env_file(tmp_path):
    """Test .env file parsing"""
    # Create a temporary .env file
    env_file = tmp_path / ".env"
    env_file.write_text("""
# Comment line
PUID=1026
PGID=100
TZ=America/Chicago

# Another comment
DATA_ROOT=/volume1/data
APPDATA_ROOT=/volume1/docker/appdata
""")
    
    result = parse_env_file(env_file)
    
    assert result["PUID"] == "1026"
    assert result["PGID"] == "100"
    assert result["TZ"] == "America/Chicago"
    assert result["DATA_ROOT"] == "/volume1/data"
    assert result["APPDATA_ROOT"] == "/volume1/docker/appdata"


def test_parse_env_file_nonexistent():
    """Test parsing a non-existent file"""
    result = parse_env_file(Path("/nonexistent/file"))
    assert result == {}


def test_build_env_text():
    """Test .env file generation"""
    values = {
        "APPDATA_ROOT": "/volume1/docker/appdata",
        "DATA_ROOT": "/volume1/data",
        "TRANSCODE_ROOT": "/volume1/docker/transcode",
        "PUID": "1026",
        "PGID": "100",
        "TZ": "America/Chicago",
        "PLEX_CLAIM": "claim-test123",
    }
    
    result = build_env_text(values)
    
    # Verify key components are present
    assert "APPDATA_ROOT=/volume1/docker/appdata" in result
    assert "DATA_ROOT=/volume1/data" in result
    assert "TRANSCODE_ROOT=/volume1/docker/transcode" in result
    assert "PUID=1026" in result
    assert "PGID=100" in result
    assert "TZ=America/Chicago" in result
    assert "PLEX_CLAIM=claim-test123" in result
    
    # Verify it starts with a comment
    assert result.startswith("# Generated by setup-ui")


def test_index_route(client):
    """Test the main index route"""
    response = client.get('/')
    assert response.status_code == 200
    assert b'<!DOCTYPE html>' in response.data or b'<html' in response.data


def test_security_headers(client):
    """Test that security headers are set"""
    response = client.get('/')
    
    # Check for security headers
    assert 'X-Content-Type-Options' in response.headers
    assert response.headers['X-Content-Type-Options'] == 'nosniff'
    
    assert 'X-Frame-Options' in response.headers
    assert response.headers['X-Frame-Options'] == 'DENY'
    
    assert 'Content-Security-Policy' in response.headers
    assert 'default-src' in response.headers['Content-Security-Policy']
    
    assert 'Cache-Control' in response.headers
    assert response.headers['Cache-Control'] == 'no-store'


def test_csrf_protection(client):
    """Test CSRF protection is enabled"""
    response = client.get('/')
    
    # Should set a CSRF cookie
    assert 'csrf' in response.headers.get('Set-Cookie', '')


def test_defaults():
    """Test that DEFAULTS dict is properly configured"""
    assert "STACK_PATH" in DEFAULTS
    assert "APPDATA_ROOT" in DEFAULTS
    assert "DATA_ROOT" in DEFAULTS
    assert "PUID" in DEFAULTS
    assert "PGID" in DEFAULTS
    assert "TZ" in DEFAULTS
    
    # Verify sensible default values
    assert DEFAULTS["PUID"].isdigit()
    assert DEFAULTS["PGID"].isdigit()
    assert "/" in DEFAULTS["DATA_ROOT"]  # Should be a path


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
