param(
  [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
  [switch]$Force
)

$ErrorActionPreference = 'Stop'

function Prompt-Value {
  param(
    [Parameter(Mandatory=$true)][string]$Name,
    [Parameter(Mandatory=$true)][string]$Prompt,
    [string]$Default,
    [switch]$Secret
  )

  $suffix = if ($Default) { " [$Default]" } else { "" }
  $fullPrompt = "$Prompt$suffix"

  if ($Secret) {
    $secure = Read-Host -Prompt $fullPrompt -AsSecureString
    if (-not $secure -or $secure.Length -eq 0) { return $Default }
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try { return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) }
    finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
  }

  $value = Read-Host -Prompt $fullPrompt
  if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
  return $value
}

$envExamplePath = Join-Path $ProjectRoot '.env.example'
$envPath        = Join-Path $ProjectRoot '.env'

if (-not (Test-Path $envExamplePath)) {
  throw "Missing .env.example at $envExamplePath"
}

$defaults = @{}
(Get-Content $envExamplePath) | ForEach-Object {
  if ($_ -match '^(?<k>[A-Za-z0-9_]+)=(?<v>.*)$') {
    $defaults[$Matches.k] = $Matches.v
  }
}

if ((Test-Path $envPath) -and (-not $Force)) {
  $resp = Read-Host -Prompt ".env already exists. Overwrite? (y/N)"
  if ($resp -notin @('y','Y','yes','YES')) {
    Write-Host "Keeping existing .env."
    exit 0
  }
}

Write-Host "Generating .env from prompts..." 

$appdataRoot   = Prompt-Value -Name 'APPDATA_ROOT'   -Prompt 'APPDATA_ROOT (Synology: /volume1/docker/appdata)' -Default $defaults.APPDATA_ROOT
$dataRoot      = Prompt-Value -Name 'DATA_ROOT'      -Prompt 'DATA_ROOT (Synology: /volume1/data)' -Default $defaults.DATA_ROOT
$transcodeRoot = Prompt-Value -Name 'TRANSCODE_ROOT' -Prompt 'TRANSCODE_ROOT (Synology: /volume1/docker/transcode)' -Default $defaults.TRANSCODE_ROOT
$puid          = Prompt-Value -Name 'PUID'           -Prompt 'PUID (DSM user id for containers)' -Default $defaults.PUID
$pgid          = Prompt-Value -Name 'PGID'           -Prompt 'PGID (DSM group id for containers)' -Default $defaults.PGID
$tz            = Prompt-Value -Name 'TZ'             -Prompt 'TZ (e.g., America/Chicago)' -Default $defaults.TZ

Write-Host "PLEX_CLAIM is optional. Paste a token only for first-time server claim." 
$plexClaim     = Prompt-Value -Name 'PLEX_CLAIM'     -Prompt 'PLEX_CLAIM' -Default $defaults.PLEX_CLAIM -Secret

$lines = @(
  "# Generated by scripts/setup.ps1 on $(Get-Date -Format s)",
  "",
  "APPDATA_ROOT=$appdataRoot",
  "DATA_ROOT=$dataRoot",
  "TRANSCODE_ROOT=$transcodeRoot",
  "",
  "PUID=$puid",
  "PGID=$pgid",
  "TZ=$tz",
  "",
  "# Optional. Leave blank after Plex is claimed.",
  "PLEX_CLAIM=$plexClaim",
  "",
  "# Optional. Usually not needed with Plex host networking.",
  "ADVERTISE_IP=$($defaults.ADVERTISE_IP)"
)

Set-Content -Path $envPath -Value ($lines -join "`n") -Encoding UTF8
Write-Host "Wrote $envPath"

# Best-effort validation if Docker is available
$dockerExe = $null
$dockerCmd = Get-Command docker -ErrorAction SilentlyContinue
if ($dockerCmd) {
  $dockerExe = $dockerCmd.Source
} elseif (Test-Path "C:\Program Files\Docker\Docker\resources\bin\docker.exe") {
  $dockerExe = "C:\Program Files\Docker\Docker\resources\bin\docker.exe"
}

if ($dockerExe) {
  try {
    Push-Location $ProjectRoot
    & $dockerExe compose config | Out-Null
    Pop-Location
    Write-Host "Validated: docker compose config OK"
  } catch {
    Write-Warning "docker compose config failed. Verify your .env paths and rerun. Error: $($_.Exception.Message)"
  }
} else {
  Write-Host "Docker CLI not found; skipped compose validation."
}
